# Generated by Django 6.0.2 on 2026-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
